# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QueVideo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('IdActividad', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField()),
                ('Video', models.CharField(max_length=64)),
                ('Observaciones', models.CharField(max_length=255)),
                ('Lugar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlanLogistica',
            fields=[
                ('IdPlanLogistica', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=64)),
                ('Descripcion', models.CharField(max_length=255)),
                ('Escaleta', models.CharField(max_length=255)),
                ('GuionTecnico', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='PlanLogistica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QueVideo.PlanLogistica'),
        ),
    ]
