# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-01 20:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QueVideo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='usuario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
