# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-12 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('QueVideo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('IdActividad', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField()),
                ('Video', models.CharField(max_length=64)),
                ('Observaciones', models.CharField(max_length=255)),
                ('Lugar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Crudo',
            fields=[
                ('IdCrudo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('Tipo', models.CharField(choices=[('V', 'Video')], default='V', max_length=50)),
                ('Archivo', models.FileField(null=True, upload_to='crudos')),
                ('url', models.CharField(default=' ', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('idEtapa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('WAITING', 'Pendiente'), ('PROCESS', 'En Proceso'), ('DONE', 'Terminado')], max_length=255)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('fecha_fin', models.DateTimeField(verbose_name='fecha de finalizacion')),
                ('etapa_type', models.CharField(choices=[('Pre', 'Pre-Produccion'), ('Pro', 'Produccion'), ('Pos', 'Post-Produccion'), ('CC', 'Control de calidad'), ('CP', 'Cierre de proyecto'), ('SR', 'Sistematizacion y resguardo')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlanLogistica',
            fields=[
                ('IdPlanLogistica', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=64)),
                ('Descripcion', models.CharField(max_length=255)),
                ('Escaleta', models.CharField(max_length=255)),
                ('GuionTecnico', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_CambioEstado',
            fields=[
                ('idSolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('solicitadoPor', models.CharField(max_length=255)),
                ('aprobadoPor', models.CharField(max_length=255)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('fecha_aprobacion', models.DateTimeField(verbose_name='fecha de aprobacion')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='PlanLogistica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QueVideo.PlanLogistica'),
        ),
    ]
