# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueVideo', '0002_auto_20180926_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crudo',
            fields=[
                ('IdCrudo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('Tipo', models.CharField(choices=[('V', 'Video')], default='V', max_length=50)),
                ('Archivo', models.FileField(null=True, upload_to='crudos')),
            ],
        ),
    ]
