# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueVideo', '0002_auto_20181012_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='fecha_fin',
            field=models.DateTimeField(verbose_name='fecha de finalizacion no definida'),
        ),
        migrations.AlterField(
            model_name='solicitud_cambioestado',
            name='aprobadoPor',
            field=models.CharField(default='No se ha aprobado', max_length=255),
        ),
        migrations.AlterField(
            model_name='solicitud_cambioestado',
            name='fecha_aprobacion',
            field=models.DateTimeField(verbose_name='fecha de aprobacion no definida'),
        ),
    ]
