# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueVideo', '0003_crudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='crudo',
            name='url',
            field=models.CharField(default=' ', max_length=2000),
        ),
    ]
