# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueVideo', '0004_crudo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudo',
            name='Nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
